// Auto-generated by capacitor-scripts/apply-overrides.mjs
//
// Universal AdMob JavaScript-to-native bridge.
//
// Exposes `window.AdMobBridge` with a complete API surface (banner,
// interstitial, rewarded, rewarded-interstitial, app-open) on top of the
// `@capacitor-community/admob` plugin (Capacitor.Plugins.AdMob).
//
// Every native callback is re-broadcast as a DOM `CustomEvent` on
// `window` so the web app can subscribe without depending on Capacitor:
//
//   admob:ready
//   admob:adLoaded         { format, error? }
//   admob:adFailedToLoad   { format, error }
//   admob:adOpened         { format }
//   admob:adClosed         { format }
//   admob:adClicked        { format }
//   admob:adImpression     { format }
//   admob:rewardEarned     { format, reward: { type, amount } }
//
// The native side decides nothing about WHEN ads are shown — the web
// app drives the entire lifecycle via these methods.

(function () {
  if (typeof window === 'undefined') return;
  if (window.AdMobBridge && window.AdMobBridge.__installed) return;

  var listeners = [];
  function emit(name, detail) {
    try {
      window.dispatchEvent(new CustomEvent('admob:' + name, { detail: detail || {} }));
    } catch (e) { /* ignore */ }
  }

  function plugin() {
    var Cap = window.Capacitor;
    if (!Cap || !Cap.Plugins || !Cap.Plugins.AdMob) return null;
    return Cap.Plugins.AdMob;
  }

  function isNative() {
    var Cap = window.Capacitor;
    return !!(Cap && Cap.isNativePlatform && Cap.isNativePlatform() && plugin());
  }

  function notNative(method) {
    return Promise.reject(new Error('[AdMobBridge] ' + method + ' unavailable: not running in the native Android shell.'));
  }

  // -------- listener wiring (idempotent) --------
  // Capacitor plugins expose `addListener(eventName, cb) => { remove() }`.
  // We register once and forward into DOM events.
  function wireListeners() {
    var p = plugin();
    if (!p || p.__bridgeWired) return;
    p.__bridgeWired = true;

    var map = {
      // Banner
      bannerAdLoaded:        ['adLoaded',       'banner'],
      bannerAdFailedToLoad:  ['adFailedToLoad', 'banner'],
      bannerAdOpened:        ['adOpened',       'banner'],
      bannerAdClosed:        ['adClosed',       'banner'],
      bannerAdClicked:       ['adClicked',      'banner'],
      bannerAdImpression:    ['adImpression',   'banner'],
      // Interstitial
      interstitialAdLoaded:        ['adLoaded',       'interstitial'],
      interstitialAdFailedToLoad:  ['adFailedToLoad', 'interstitial'],
      interstitialAdShowed:        ['adOpened',       'interstitial'],
      interstitialAdDismissed:     ['adClosed',       'interstitial'],
      interstitialAdClicked:       ['adClicked',      'interstitial'],
      interstitialAdImpression:    ['adImpression',   'interstitial'],
      interstitialAdFailedToShow:  ['adFailedToLoad', 'interstitial'],
      // Rewarded
      rewardedVideoAdLoaded:        ['adLoaded',       'rewarded'],
      rewardedVideoAdFailedToLoad:  ['adFailedToLoad', 'rewarded'],
      rewardedVideoAdShowed:        ['adOpened',       'rewarded'],
      rewardedVideoAdDismissed:     ['adClosed',       'rewarded'],
      rewardedVideoAdFailedToShow:  ['adFailedToLoad', 'rewarded'],
      onRewardedVideoAdReward:      ['rewardEarned',   'rewarded'],
      // Rewarded interstitial (community plugin uses same prefix)
      rewardedInterstitialAdLoaded:        ['adLoaded',       'rewardedInterstitial'],
      rewardedInterstitialAdFailedToLoad:  ['adFailedToLoad', 'rewardedInterstitial'],
      rewardedInterstitialAdShowed:        ['adOpened',       'rewardedInterstitial'],
      rewardedInterstitialAdDismissed:     ['adClosed',       'rewardedInterstitial'],
      onRewardedInterstitialAdReward:      ['rewardEarned',   'rewardedInterstitial'],
      // App open
      appOpenAdLoaded:        ['adLoaded',       'appOpen'],
      appOpenAdFailedToLoad:  ['adFailedToLoad', 'appOpen'],
      appOpenAdShowed:        ['adOpened',       'appOpen'],
      appOpenAdDismissed:     ['adClosed',       'appOpen'],
    };

    Object.keys(map).forEach(function (event) {
      try {
        var l = p.addListener(event, function (data) {
          var info = map[event];
          var detail = Object.assign({ format: info[1] }, data || {});
          emit(info[0], detail);
        });
        if (l && typeof l.then === 'function') l.then(function (h) { listeners.push(h); });
        else listeners.push(l);
      } catch (e) { /* event may not exist on this plugin version — ignore */ }
    });
  }

  function call(method, args) {
    var p = plugin();
    if (!p || typeof p[method] !== 'function') return notNative(method);
    wireListeners();
    return p[method](args || {});
  }

  var Bridge = {
    __installed: true,
    isNative: isNative,
    isReady: function () { return isNative(); },

    initialize: function (opts) {
      if (!isNative()) return notNative('initialize');
      wireListeners();
      return plugin().initialize(Object.assign({}, opts || {}, {
        requestTrackingAuthorization: true,
        testingDevices: [],
        initializeForTesting: false,
      })).then(function (r) {
        emit('ready', {});
        return r;
      });
    },

    requestConsentInfo:   function (opts) { return call('requestConsentInfo', opts); },
    showConsentForm:      function (opts) { return call('showConsentForm', opts); },
    resetConsentInfo:     function ()     { return call('resetConsentInfo'); },
    trackingAuthorizationStatus: function () { return call('trackingAuthorizationStatus'); },
    requestTrackingAuthorization: function () { return call('requestTrackingAuthorization'); },

    // -------- Banner --------
    loadBanner: function (opts) {
      // The community plugin uses showBanner() to load+show; we expose
      // load/show as separate intents but both call showBanner so the web
      // app's flow matches Android documentation.
      return call('showBanner', opts);
    },
    showBanner:   function (opts) { return call('showBanner', opts); },
    hideBanner:   function ()     { return call('hideBanner'); },
    resumeBanner: function ()     { return call('resumeBanner'); },
    removeBanner: function ()     { return call('removeBanner'); },

    // -------- Interstitial --------
    loadInterstitial: function (opts) { return call('prepareInterstitial', opts); },
    showInterstitial: function ()     { return call('showInterstitial'); },

    // -------- Rewarded --------
    loadRewarded: function (opts) { return call('prepareRewardVideoAd', opts); },
    showRewarded: function ()     { return call('showRewardVideoAd'); },

    // -------- Rewarded interstitial --------
    loadRewardedInterstitial: function (opts) { return call('prepareRewardInterstitialAd', opts); },
    showRewardedInterstitial: function ()     { return call('showRewardInterstitialAd'); },

    // -------- App open --------
    loadAppOpen: function (opts) { return call('prepareAppOpenAd', opts); },
    showAppOpen: function ()     { return call('showAppOpenAd'); },

    // Manual listener escape hatch (in addition to DOM events).
    on: function (eventName, cb) {
      var handler = function (e) { cb(e.detail); };
      window.addEventListener('admob:' + eventName, handler);
      return function () { window.removeEventListener('admob:' + eventName, handler); };
    },
  };

  window.AdMobBridge = Bridge;

  // Auto-wire listeners as soon as Capacitor is present.
  function tryWire() {
    if (isNative()) { wireListeners(); emit('ready', {}); return true; }
    return false;
  }
  if (!tryWire()) {
    var tries = 0;
    var t = setInterval(function () {
      if (tryWire() || ++tries > 40) clearInterval(t);
    }, 250);
  }
})();
