// Auto-generated by capacitor-scripts/apply-overrides.mjs
// Exposes window.PlayBilling — a Promise-based wrapper around the native
// PlayBillingNative JavascriptInterface registered by MainActivity.java.
//
// Native call protocol (see PlayBillingPlugin.java):
//   PlayBillingNative.<method>(args..., callbackId)
//   → resolves via window.PlayBilling.__resolve(callbackId, payload)
//   → events broadcast via window.PlayBilling.__emit(eventName, payload)
(function () {
  if (typeof window === 'undefined') return;
  if (window.PlayBilling && window.PlayBilling.__installed) return;

  var pending = Object.create(null);
  var listeners = Object.create(null);
  var nextId = 1;

  function newId() { return 'pb_' + (nextId++) + '_' + Date.now().toString(36); }

  function native() {
    return (typeof window !== 'undefined') ? window.PlayBillingNative : null;
  }

  function call(method, args) {
    return new Promise(function (resolve, reject) {
      var n = native();
      if (!n || typeof n[method] !== 'function') {
        reject(new Error('PlayBillingNative.' + method + ' unavailable — running outside the native Android build?'));
        return;
      }
      var id = newId();
      pending[id] = { resolve: resolve, reject: reject };
      try {
        // All native methods take (...args, callbackId)
        var allArgs = (args || []).concat([id]);
        n[method].apply(n, allArgs);
      } catch (e) {
        delete pending[id];
        reject(e);
      }
    });
  }

  function on(eventName, fn) {
    (listeners[eventName] = listeners[eventName] || []).push(fn);
    return function off() {
      var list = listeners[eventName];
      if (!list) return;
      var i = list.indexOf(fn);
      if (i >= 0) list.splice(i, 1);
    };
  }

  var PlayBilling = {
    __installed: true,
    isAvailable: function () { return !!native(); },

    // Lifecycle
    connect: function () { return call('connect', []); },
    destroy: function () { try { var n = native(); n && n.destroy && n.destroy(); } catch (e) {} },

    // Catalog
    queryProducts: function (productIds) {
      return call('queryProducts', [JSON.stringify(productIds || [])]);
    },
    querySubscriptions: function (productIds) {
      return call('querySubscriptions', [JSON.stringify(productIds || [])]);
    },

    // Purchase flow
    launchPurchase: function (productId) { return call('launchPurchase', [String(productId)]); },
    acknowledgePurchase: function (purchaseToken) { return call('acknowledgePurchase', [String(purchaseToken)]); },
    consumePurchase: function (purchaseToken) { return call('consumePurchase', [String(purchaseToken)]); },

    // Inventory of existing entitlements; productType: "inapp" | "subs"
    queryPurchases: function (productType) { return call('queryPurchases', [String(productType || 'inapp')]); },

    // Event API
    on: on,
    addListener: on, // alias matching Capacitor style

    // Internal — invoked from the native side
    __resolve: function (callbackId, payload) {
      var entry = pending[callbackId];
      if (!entry) return;
      delete pending[callbackId];
      if (payload && payload.error) entry.reject(new Error(payload.error));
      else entry.resolve(payload);
    },
    __emit: function (eventName, payload) {
      var list = listeners[eventName];
      if (!list) return;
      // Mirror to a DOM event so non-PlayBilling code can subscribe too
      try {
        window.dispatchEvent(new CustomEvent('playbilling:' + eventName, { detail: payload }));
      } catch (e) {}
      for (var i = 0; i < list.length; i++) {
        try { list[i](payload); } catch (e) { console.error('[PlayBilling listener]', e); }
      }
    },
  };

  window.PlayBilling = PlayBilling;

  // Auto-connect once the WebView is ready so the first purchase call is fast.
  function autoConnect() {
    if (!PlayBilling.isAvailable()) return;
    PlayBilling.connect().then(function () {
      window.dispatchEvent(new CustomEvent('playbilling:ready'));
    }).catch(function (err) { console.warn('[PlayBilling auto-connect failed]', err); });
  }
  if (document.readyState === 'complete') autoConnect();
  else window.addEventListener('load', autoConnect);
})();
