
ALTER TABLE public.build_configs
  ADD COLUMN IF NOT EXISTS enable_capacitor boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS custom_html text,
  ADD COLUMN IF NOT EXISTS custom_css text,
  ADD COLUMN IF NOT EXISTS custom_js text,
  ADD COLUMN IF NOT EXISTS build_type text NOT NULL DEFAULT 'aab',
  ADD COLUMN IF NOT EXISTS user_agent_override text,
  ADD COLUMN IF NOT EXISTS enable_pull_to_refresh boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_native_splash boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_offline_page boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_push_notifications boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_camera boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_microphone boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_location boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_storage boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_sms boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_contacts boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_phone_state boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_vibrate boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_clipboard boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_share boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_biometric boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_bluetooth boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_nfc boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_calendar boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_file_download boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_file_upload boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_geolocation boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS block_screenshots boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS keep_screen_on boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS fullscreen_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS hide_status_bar boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allow_zoom boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS dark_mode_force boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allow_external_links boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS cache_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_cleartext boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS swipe_back_navigation boolean NOT NULL DEFAULT true;
